{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fullstack-app-ingress
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          # Frontend served at /frontend/
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-deployment-service
                port:
                  number: 80

          # Backend served at /backend/
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend-deployment-service
                port:
                  number: 2000
{{- end }}